version: '3'

services:
  mysql-database:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: api
      MYSQL_PASSWORD: 3opijdf2@!ad
      MYSQL_ROOT_PASSWORD: 3opijdf2@!ad
    ports:
      - "3306:3307"
    volumes:
      - .var/data:/var/lib/mysql

  api:
    image: herik-lorencao/gestao-produtos
    environment:
      DB_HOST: mysql-database
    ports:
      - "10000:10000"
volumes:
  db-volume:
