version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: gestaoprodutos
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: caelum/clines-api
    environment:
      DB_HOST: database
    ports:
      - "8080:8080"
volumes:
  db-volume: